---
title: "Comparisons: Heat"
author: "Carlos Dobler -"
date: "2023-02-06"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F,
                      fig.height=4.1*3,#32, 
                      fig.width=9.7, 
                      out.width="95%")


library(tidyverse)
library(lubridate)
library(stars)
library(furrr)
library(units)
library(colorspace)
library(patchwork)
library(colorspace)

dir_mosaicked <- "/mnt/bucket_mine/results/global_heat_pf/03_mosaicked/heat/"
dir_originals <- "/mnt/pers_disk/originals"

# if(dir.exists(dir_originals)){
#   unlink(dir_originals, recursive = T)
#   dir.create(dir_originals)
#   "gsutil -m cp gs://wcdi_production/heat_module/*.nc {dir_originals}/" %>%
#   str_glue() %>%
#   system()
# }


tb_vars <-
  read_csv("/mnt/bucket_mine/pf_variable_table.csv") %>% 
  suppressMessages() %>% 
  .[1:16,] %>% 
  mutate(var_orig = c("sum_days_tasmax_above_32C",
                      "sum_days_tasmax_above_35C",
                      "sum_days_tasmax_above_38C",
                      "mean_tasmax_10day",
                      "mean_tasmax",
                      "sum_days_tasmax_below_0C",
                      
                      "sum_days_tasmin_above_20C",
                      "sum_days_tasmin_above_25C",
                      "mean_tasmin",
                      "sum_days_tasmin_below_0C",
                      
                      "sum_days_wetbulbmax_above_26C",
                      "sum_days_wetbulbmax_above_28C",
                      "sum_days_wetbulbmax_above_30C",
                      "sum_days_wetbulbmax_above_32C",
                      "mean_wetbulbmax_10day",
                      
                      "mean_tas"
                      ))



land_pol <- 
  "/mnt/bucket_mine/misc_data/ne_110m_land/" %>% 
  st_read() %>%
  mutate(a = 1) %>% 
  select(a)

land_rast_0.1 <- 
  c(st_point(c(-180, -90)),
  st_point(c(180, 90))) %>%
  st_bbox() %>%
  st_set_crs(4326) %>% 
  st_as_stars(dx = 0.1, dy = 0.1, values = NA) %>% 
  {st_rasterize(land_pol, .)}





func_maps <- function(i, slices = c(1,3,6)){
  
  final_name <- tb_vars$final_name[i]
  var_orig <- tb_vars$var_orig[i]

  s_old <- 
    dir_originals %>%
    list.files(full.names = T) %>% 
    str_subset(str_glue("annual_{var_orig}.nc")) %>%
    read_ncdf(make_time = F) %>% 
    select(2) %>% 
    slice(time, slices)
  
  if(str_detect(names(s_old), "median")){
    stat <- "perc50"
  } else {
    stat <- "mean"
  }
  
  s_new <- 
    dir_mosaicked %>% 
    list.files(full.names = T) %>% 
    str_subset(str_glue("{final_name}_")) %>% 
    read_ncdf(var = stat) %>% 
    st_set_dimensions("wl", values = seq(0.5, 3, by = 0.5)) %>% 
    slice(wl, slices) %>% 
    setNames("v")
  
  s_old <- 
    s_old %>% 
    st_warp(s_new) %>% 
    setNames("v") %>%
    mutate(v = set_units(v, NULL),
           v = ifelse(v == -99999, NA, v))
  
  list(s_new, s_old)
}



func_land <- function(m, mask){
  
  m[is.na(mask)] <- NA
  return(m)
  
}




func_plot <- function(foo, clamp = NA, bks = NA, nm){
  
  tb <- 
    foo %>% 
    as_tibble()

  if(all(!is.na(clamp))){
    tb <-
      tb %>% 
      mutate(v = raster::clamp(v, clamp[1], clamp[2]))
  }
  
  p <- 
    tb %>% 
    ggplot(aes(lon, lat, fill = v)) +
    geom_raster() +
    facet_wrap(~wl, ncol = 1) +
    coord_equal(ylim = c(-60, 78), xlim = c(-160, 155)) +
    theme(axis.title = element_blank(),
          legend.position = "bottom") +
    
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    
    guides(fill = guide_coloursteps(barwidth = 20, 
                                    barheight = 0.5, 
                                    ticks = F, 
                                    show.limits = F,
                                    even.steps = F))
  
  
  
  if(all(!is.na(bks))){
    
    p <- 
      p + 
      scale_fill_binned_diverging("blue-red3",
                                  rev = T,
                                  na.value = "transparent",
                                  breaks = bks,
                                  name = str_glue("{nm}   "))
    
  } else {
    
    p <- 
      p + 
      scale_fill_binned_diverging("blue-red3",
                                  rev = T,
                                  na.value = "transparent",
                                  name = str_glue("{nm}   "))
    
  }
      
  return(p)
    
}


```


## Days above 32C
```{r}

m <- func_maps(1)

land_rast_0.2 <- 
  st_warp(land_rast_0.1, m[[1]] %>% slice(wl, 1))

m <- 
  m %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")


```


## Days above 35C
```{r}

m <- 
  func_maps(2) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Days above 38C
```{r}

m <- 
  func_maps(3) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Ten hottests days
```{r}

m <- 
  func_maps(4) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-8,8),
          bks = c(-8, -5, -3, -2, -1, 1, 2, 3, 5, 8),
          nm = "degC")

```


## Average daytime temperature
```{r}

m <- 
  func_maps(5) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-8,8),
          bks = c(-8, -5, -3, -2, -1, 1, 2, 3, 5, 8),
          nm = "degC")

```


## Freezing days
```{r}

m <- 
  func_maps(6) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Nights above 20C
```{r}

m <- 
  func_maps(7) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "nights")

```


## Nights above 25C
```{r}

m <- 
  func_maps(8) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "nights")

```


## Average nighttime temperature
```{r}

m <- 
  func_maps(9) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-8,8),
          bks = c(-8, -5, -3, -2, -1, 1, 2, 3, 5, 8),
          nm = "degC")

```


## Frost nights
```{r}

m <- 
  func_maps(10) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "nights")

```


## Days above 26C wetbulb
```{r}

m <- 
  func_maps(11) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Days above 28C wetbulb
```{r}

m <- 
  func_maps(12) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Days above 30C wetbulb
```{r}

m <- 
  func_maps(13) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Days above 32C wetbulb
```{r}

m <- 
  func_maps(14) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-100,100),
          bks = c(-100, -80, -50, -30, -15, -5, 5, 15, 30, 50, 80, 100),
          nm = "days")

```


## Ten hottest wetbulb days
```{r}

m <- 
  func_maps(15) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-8,8),
          bks = c(-8, -5, -3, -2, -1, 1, 2, 3, 5, 8),
          nm = "degC")

```


## Average temperature
```{r}

m <- 
  func_maps(16) %>% 
  map(func_land, land_rast_0.2)

s_diff <- m[[1]] - m[[2]]

func_plot(foo = s_diff,
          clamp = c(-8,8),
          bks = c(-8, -5, -3, -2, -1, 1, 2, 3, 5, 8),
          nm = "degC")

```
