---
title: "Water module exhibits"
author: "Carlos Dobler -"
date: "2023-02-13"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F,
                      fig.height=4.1*7,#32, 
                      fig.width=9.7, 
                      out.width="95%")


library(tidyverse)
library(lubridate)
library(stars)
library(furrr)
library(units)
library(colorspace)
library(patchwork)

dir_mosaicked <- "/mnt/bucket_mine/results/global_heat_pf/03_mosaicked/"

tb_vars <-
  read_csv("/mnt/bucket_mine/pf_variable_table.csv") %>% 
  suppressMessages()

derived_vars <- 
  tb_vars %>% 
  pull(final_name)

dir_mosaicked <- "/mnt/bucket_mine/results/global_heat_pf/03_mosaicked/"


windows <- tibble(x1 = c(-130, -90, -15,   5, 40, 75,  95),
                  y1 = c(  10, -30,   5, -25, 10, 20, -35))


land_pol <- 
  "/mnt/bucket_mine/misc_data/ne_110m_land/" %>% 
  st_read() %>%
  mutate(a = 1) %>% 
  select(a)


land_rast_0.1 <- 
  c(st_point(c(-180, -90)),
  st_point(c(180, 90))) %>%
  st_bbox() %>%
  st_set_crs(4326) %>% 
  st_as_stars(dx = 0.1, dy = 0.1, values = NA) %>% 
  {st_rasterize(land_pol, .)}

wls <- seq(0.5, 3, 0.5)

fn_plot <- function(x1, y1, slices = c(1,4,6), type, u){
  
  tb <- 
    s %>% 
    slice(wl, slices) %>%
    st_set_dimensions("wl", value = wls[slices]) %>%
    # select(mean) %>% 
    filter(lon > x1,
           lon < x1+60,
           lat > y1,
           lat < y1+50) %>% 
    as_tibble()
  
  dif <- 
    tb %>% 
    pull(mean) %>% 
    range(na.rm = T) %>% 
    diff()
  
  if(dif != 0){
    
    q <- quantile(tb$mean, c(0.02, 0.98), na.rm = T)
    
    if(diff(q) > 0.001){
      
      tb <- 
        tb %>% 
        mutate(mean = raster::clamp(mean, q[1], q[2]))
      
    }
    
    p <- 
      tb %>% 
      ggplot(aes(lon, lat, fill = mean)) +
      geom_raster() +
      facet_wrap(~wl, ncol = 3) +
      theme(axis.title = element_blank(),
            legend.position = "bottom") +
      coord_equal() +
      scale_x_continuous(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0)) +
      guides(fill = guide_colourbar(barwidth = 15, 
                                    barheight = 0.5, 
                                    ticks = F, 
                                    show.limits = T
                                    )
             )
    
    if(type == "seq"){
      
      p +
        scale_fill_continuous_sequential("plasma",
                                         rev = F,
                                         na.value = "transparent",
                                         name = str_glue("{u}  "))
      
    } else if(type == "div"){
      
      p +
        scale_fill_continuous_divergingx("temps",
                                         rev = T,
                                         na.value = "transparent",
                                         name = str_glue("{u}  "))
      
      
    }
  
  } else {
    
    ggplot() + theme_void()
    
  }
  
}

```


## Change in total annual precipitation
```{r}

s <- 
  dir_mosaicked %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[17]}_")) %>% 
  str_subset("v02") %>% 
  read_ncdf(var = "perc50") %>% 
  setNames("mean")

land_rast_0.2 <- 
  st_warp(land_rast_0.1, s %>% slice(wl, 1))

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1){
  
  fn_plot(x1,y1, slices = c(2,4,6), type = "div", u = "mm")  
  
}) %>%
  wrap_plots(ncol = 1)

```


## Change in 90 wettest days
```{r}

s <- 
  dir_mosaicked %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[18]}_")) %>% 
  str_subset("v02") %>% 
  read_ncdf(var = "perc50") %>% 
  setNames("mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1){
  
  fn_plot(x1,y1, slices = c(2,4,6), type = "div", u = "mm")  
  
}) %>%
  wrap_plots(ncol = 1)

```


## Change in snowy days
```{r}

s <- 
  dir_mosaicked %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[21]}_")) %>% 
  str_subset("v02") %>% 
  read_ncdf(var = "perc50") %>% 
  setNames("mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1){
  
  fn_plot(x1,y1, slices = c(2,4,6), type = "div", u = "days")  
  
}) %>%
  wrap_plots(ncol = 1)

```


## Change in dry hot days
```{r}

s <- 
  dir_mosaicked %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[22]}_")) %>% 
  str_subset("v02") %>% 
  read_ncdf(var = "perc50") %>% 
  setNames("mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1){
  
  fn_plot(x1,y1, slices = c(2,4,6), type = "div", u = "days")  
  
}) %>%
  wrap_plots(ncol = 1)

```


