---
title: "Minimum heat exhibits"
author: "Carlos Dobler -"
date: "2022-11-17"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F,
                      fig.height=32, 
                      fig.width=9, 
                      out.width="100%")


source(here::here("scripts/setup.R"))
library(patchwork)

var_input <- "minimum_temperature"

derived_vars <- 
  tb_vars %>% 
  filter(var_input == {{var_input}}) %>% 
  pull(final_name)

dir_results <- "/mnt/bucket_mine/results/global_heat_pf/03_mosaicked/"

windows <- tibble(area = c("NAM", "SAM", "AFR", "CAS", "AUS"),
                  x1 = c(-130, -100, -15, 30, 95),
                  y1 = c(15, -20, 0, 15, -35))



land_pol <- 
  "/mnt/bucket_mine/misc_data/ne_110m_land/" %>% 
  st_read() %>%
  mutate(a = 1) %>% 
  select(a)


land_rast_0.1 <- 
  c(st_point(c(-180, -90)),
  st_point(c(180, 90))) %>%
  st_bbox() %>%
  st_set_crs(4326) %>% 
  st_as_stars(dx = 0.1, dy = 0.1, values = NA) %>% 
  {st_rasterize(land_pol, .)}


fn_plot <- function(x1, y1, ...){
  
  s %>% 
      st_set_dimensions("warming_levels", value = seq(0.5, 3.0, 0.5)) %>% 
      select(mean) %>% 
      filter(lon > x1,
             lon < x1+60,
             lat > y1,
             lat < y1+50) %>% 
      as_tibble() %>% 
      
      ggplot(aes(lon, lat, fill = mean)) +
      geom_raster() +
      colorspace::scale_fill_binned_sequential("plasma", 
                                               rev = F,
                                               na.value = "transparent",
                                               name = NULL,
                                               n.breaks = 13) +
      facet_wrap(~warming_levels, ncol = 3) +
      theme(axis.title = element_blank(),
            legend.position = "bottom") +
      coord_equal() +
      guides(fill = guide_colourbar(barwidth = 25, barheight = 0.5, ticks = F))
  
}

```


## Days above 20C
```{r}

s <- 
  dir_results %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[1]}_")) %>% 
  read_ncdf(var = "mean")

land_rast_0.2 <- 
  st_warp(land_rast_0.1, s %>% slice(warming_levels, 1))

s[is.na(land_rast_0.2)] <- NA

pmap(windows, fn_plot) %>% 
  wrap_plots(ncol = 1)


```


## Days above 25C

```{r}

s <- 
  dir_results %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[2]}_")) %>% 
  read_ncdf(var = "mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, fn_plot) %>% 
  wrap_plots(ncol = 1)


```


## Nighttime temperature

```{r}

s <- 
  dir_results %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[3]}_")) %>% 
  read_ncdf(var = "mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, fn_plot) %>% 
  wrap_plots(ncol = 1)


```


## Days below 0C

```{r}

s <- 
  dir_results %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[4]}_")) %>% 
  read_ncdf(var = "mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, fn_plot) %>% 
  wrap_plots(ncol = 1)


```

