---
title: "Land module exhibits"
author: "Carlos Dobler -"
date: "2023-01-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F,
                      fig.height=18,#32, 
                      fig.width=9, 
                      out.width="100%")


source(here::here("scripts/setup.R"))
library(patchwork)

derived_vars <- 
  tb_vars %>% 
  .[23:25,] %>% 
  pull(final_name)

dir_results <- "/mnt/bucket_mine/results/global_heat_pf/03_mosaicked/"

windows <- tibble(area = c("NAM", "SAM", "AFR", "CAS", "AUS"),
                  x1 = c(-130, -100, -15, 30, 95),
                  y1 = c(15, -20, 0, 15, -35))



land_pol <- 
  "/mnt/bucket_mine/misc_data/ne_110m_land/" %>% 
  st_read() %>%
  mutate(a = 1) %>% 
  select(a)


land_rast_0.1 <- 
  c(st_point(c(-180, -90)),
  st_point(c(180, 90))) %>%
  st_bbox() %>%
  st_set_crs(4326) %>% 
  st_as_stars(dx = 0.1, dy = 0.1, values = NA) %>% 
  {st_rasterize(land_pol, .)}


fn_plot <- function(x1, y1, slices = c(2,4,6), ...){
  
  tb <- 
    s %>% 
    slice(warming_levels, slices) %>%
    st_set_dimensions("warming_levels", value = 1:3) %>%
    select(mean) %>% 
    filter(lon > x1,
           lon < x1+60,
           lat > y1,
           lat < y1+50) %>% 
    as_tibble()
  
  dif <- 
    tb %>% 
    pull(mean) %>% 
    range(na.rm = T) %>% 
    diff()
  
  if(dif != 0){
    
    q <- quantile(tb$mean, c(0.02, 0.98), na.rm = T)
    
    if(diff(q) > 0.001){
      
      tb <- 
        tb %>% 
        mutate(mean = raster::clamp(mean, q[1], q[2]))
      
    }
    
    tb %>% 
      ggplot(aes(lon, lat, fill = mean)) +
      geom_raster() +
      facet_wrap(~warming_levels, ncol = 3) +
      theme(axis.title = element_blank(),
            legend.position = "bottom") +
      coord_equal() +
      guides(fill = guide_colourbar(barwidth = 15, barheight = 0.5, ticks = F, show.limits = T))
  
  } else {
    
    ggplot() + theme_void()
    
  }
  
}

```


## Change in water balance
```{r}

s <- 
  dir_results %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[1]}_")) %>% 
  read_ncdf(var = "mean")

land_rast_0.2 <- 
  st_warp(land_rast_0.1, s %>% slice(warming_levels, 1))

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1, ...){
  
  fn_plot(x1,y1) +
  colorspace::scale_fill_binned_diverging(rev = T,
                                              na.value = "transparent",
                                              name = NULL,
                                              breaks = c(-3, -1.2, -0.8, -0.4, 0.4, 0.8, 1.2, 3)#,
                                              # limits = c(-3,3)
                                              )  
  
}) %>%
  wrap_plots(ncol = 1)




```


## Likelihood of year-plus drought
```{r}

s <- 
  dir_results %>% 
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[2]}_")) %>%
  read_ncdf(var = "mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1, ...){
  
  fn_plot(x1,y1) +
  colorspace::scale_fill_binned_sequential("plasma",
                                           rev = T,
                                           na.value = "transparent",
                                           name = NULL,
                                           n.breaks = 7
                                           # breaks = c(0, 0.1, 0.33, 0.5, 0.6, 0.9, 1)#,
                                           # limits = c(-3,3)
  )  
  
}) %>%
  wrap_plots(ncol = 1)

```


## 
```{r}

s <-
  dir_results %>%
  list.files(full.names = T) %>%
  str_subset(str_glue("{derived_vars[3]}_")) %>%
  read_ncdf(var = "mean")

s[is.na(land_rast_0.2)] <- NA

pmap(windows, function(x1,y1, ...){
  
  fn_plot(x1,y1) +
  colorspace::scale_fill_binned_sequential("plasma",
                                           rev = T,
                                           na.value = "transparent",
                                           name = NULL,
                                           n.breaks = 7
                                           # breaks = c(0, 0.1, 0.33, 0.5, 0.6, 0.9, 1)#,
                                           # limits = c(-3,3)
  )  
  
}) %>%
  wrap_plots(ncol = 1)


```


